string target_link

# start joint position
sensor_msgs/JointState start_position 	# leave empty to use current position

sensor_msgs/JointState goal_position    # looks into this one first
geometry_msgs/Transform goal_pose		# use this one when 'goal_position' is empty

bool execute
---
trajectory_msgs/JointTrajectory output_trajectory
bool success
string message
