string PATTERN_USER_ACTIONS="^user*"

string search_pattern			# only actions matching this pattern will be returned, leave empty to get all actions
---
string[] action_ids
bool succeeded
string err_msg